version: "3"
services:
  front:
    image: "node:15"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
      - "6006:6006"
    command: yarn start
